#! /bin/bash
actions="
logout killall X
shutdown halt
reboot reboot
xterm
urxvt
brave
htop
gpick
nitrogen
new sed -i \"/^new/i\$(echo | dmenu -p \"Enter new name and action\")\" '$0'"
result=$(echo "$actions" | dmenu -l "10" -fn "mononokiNerdFont-13" -nb "#2C323E" -nf "#5FD8EC" -sb "#4B666C" -sf "#FFFFFF" -x "500" -y "50" -z "1000")
cmd=$(echo "$result" | cut -d' ' -f2-)
[ -n "$cmd" ] && eval setsid setsid "$cmd"
exit 0