#!/usr/bin/env bash

# dmenu theming
. $HOME/.local/bin/dmenu-theming

prompt="-p Launch:"
colors="-nb \#2C323E -nf \#EFB060 -sb \#414654 -sf \#E5E9F0"

j4-dmenu-desktop --dmenu="dmenu -i $prompt $lines $colors $font $xoffset $yoffset $width"

