#!/usr/bin/env bash

# path:   /home/klassiker/.local/share/repos/dmenu/scripts/dmenu_man.sh
# author: klassiker [mrdotx]
# github: https://github.com/mrdotx/dmenu
# date:   2022-07-08T19:14:52+0200

select=$(man -k -l '' \
    | sort \
    | dmenu -l "10" -fn "mononokiNerdFont-13" -nb "#2C323E" -nf "#5FD8EC" -sb "#4B666C" -sf "#FFFFFF" -x "500" -y "50" -z "1000" -p "man »" \
    | cut -d ' ' -f1,2 \
    | tr -d ' ' \
)

# terminal to open manual
terminal="urxvt"

[ -n "$select" ] \
    && $terminal -T "man floating" -e man "$select"